# Generated by Django 4.1.5 on 2023-03-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title of the project')),
                ('description', models.TextField(max_length=300, verbose_name='Info about the project')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Image of the project')),
                ('date', models.DateField(verbose_name='Finish date of the project')),
                ('url', models.URLField(verbose_name='URL of the project (GitHub or web link)')),
                ('languages', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('mysql', 'MySql'), ('postgresql', 'PostgreSQL'), ('django', 'Django'), ('html', 'HTML'), ('css', 'CSS')], max_length=30)),
            ],
        ),
    ]
