# Generated by Django 4.1.5 on 2023-03-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_projects_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(help_text='Finish date of the project', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Info about the project', max_length=300, verbose_name='Information'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(help_text='Image of the project', upload_to='projects/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='languages',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('mysql', 'MySql'), ('postgresql', 'PostgreSQL'), ('django', 'Django'), ('html', 'HTML'), ('css', 'CSS')], help_text='Language used to develop this project', max_length=30, verbose_name='Languages'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Title of the project', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(help_text='URL of the project (GitHub or web link)', verbose_name='URL'),
        ),
    ]
