# Generated by Django 4.1.5 on 2023-03-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_project_date_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='languages',
            field=models.CharField(help_text='Languages used to develop this project', max_length=150, verbose_name='Languages'),
        ),
    ]
