# Generated by Django 4.1.5 on 2023-03-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_project_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='languages',
            field=models.TextField(help_text='Languages used to develop this project', max_length=150, verbose_name='Languages'),
        ),
    ]
