# Generated by Django 4.1.5 on 2023-03-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_project_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='image1',
            field=models.ImageField(default=0, help_text='Image of the project', upload_to='projects/', verbose_name='First image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='image2',
            field=models.ImageField(default=0, help_text='Second image of the project', upload_to='projects/', verbose_name='Second image'),
            preserve_default=False,
        ),
    ]
